name: Docker Image CI

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.11.2
    steps:
    - run: python --version
    - uses: actions/checkout@v3
    - name: Run a python file
      run: python aps.py  
